/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export interface AtlasSchemaRevisions {
  applied: Generated<number>
  description: string
  error: string | null
  errorStmt: string | null
  executedAt: string
  executionTime: number
  hash: string
  operatorVersion: string
  partialHashes: string | null
  total: Generated<number>
  type: Generated<number>
  version: string
}

export interface CompanyGithubUsers {
  createdAt: Generated<string>
  displayName: string
  email: string | null
  isActive: Generated<number>
  login: string
  name: string | null
  pictureUrl: string | null
  updatedAt: string
  userId: string | null
}

export interface ExportSettings {
  clientEmail: string
  createdAt: Generated<string>
  id: string
  privateKey: string
  sheetId: string
  updatedAt: string
}

export interface Integrations {
  id: string
  method: string
  privateToken: string | null
  provider: string
}

export interface OrganizationSettings {
  createdAt: Generated<string>
  excludedUsers: Generated<string>
  id: string
  isActive: Generated<number>
  refreshRequestedAt: string | null
  releaseDetectionKey: Generated<string>
  releaseDetectionMethod: Generated<string>
  updatedAt: string
}

export interface PullRequestReviewers {
  pullRequestNumber: number
  repositoryId: string
  requestedAt: string | null
  reviewer: string
}

export interface PullRequestReviews {
  id: string
  pullRequestNumber: number
  repositoryId: string
  reviewer: string
  state: string
  submittedAt: string
  url: string
}

export interface PullRequests {
  additions: number | null
  author: string
  changedFiles: number | null
  codingTime: number | null
  deletions: number | null
  deployTime: number | null
  firstCommittedAt: string | null
  firstReviewedAt: string | null
  mergedAt: string | null
  number: number
  pickupTime: number | null
  pullRequestCreatedAt: string
  releasedAt: string | null
  repo: string
  repositoryId: string
  reviewTime: number | null
  sourceBranch: string
  state: string
  targetBranch: string
  title: string
  totalTime: number | null
  updatedAt: string | null
  url: string
}

export interface Repositories {
  createdAt: Generated<string>
  id: string
  integrationId: string
  owner: string
  provider: string
  releaseDetectionKey: Generated<string>
  releaseDetectionMethod: Generated<string>
  repo: string
  teamId: string | null
  updatedAt: string
}

export interface Teams {
  createdAt: Generated<string>
  displayOrder: Generated<number>
  id: string
  name: string
}

export interface DB {
  atlasSchemaRevisions: AtlasSchemaRevisions
  companyGithubUsers: CompanyGithubUsers
  exportSettings: ExportSettings
  integrations: Integrations
  organizationSettings: OrganizationSettings
  pullRequestReviewers: PullRequestReviewers
  pullRequestReviews: PullRequestReviews
  pullRequests: PullRequests
  repositories: Repositories
  teams: Teams
}
