/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Accounts {
  accessToken: string | null;
  accessTokenExpiresAt: string | null;
  accountId: string;
  createdAt: string;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: string | null;
  scope: string | null;
  updatedAt: string;
  userId: string;
}

export interface CompanyGithubUsers {
  createdAt: Generated<string>;
  displayName: string;
  email: string | null;
  login: string;
  name: string | null;
  organizationId: string;
  pictureUrl: string | null;
  updatedAt: string;
  userId: string | null;
}

export interface ExportSettings {
  clientEmail: string;
  createdAt: Generated<string>;
  id: string;
  organizationId: string;
  privateKey: string;
  sheetId: string;
  updatedAt: string;
}

export interface Integrations {
  id: string;
  method: string;
  organizationId: string;
  privateToken: string | null;
  provider: string;
}

export interface Invitations {
  email: string;
  expiresAt: string;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface Members {
  createdAt: string;
  id: string;
  organizationId: string;
  role: string;
  userId: string;
}

export interface Organizations {
  createdAt: Generated<string>;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string | null;
}

export interface OrganizationSettings {
  createdAt: Generated<string>;
  excludedUsers: Generated<string>;
  id: string;
  isActive: Generated<number>;
  organizationId: string;
  releaseDetectionKey: Generated<string>;
  releaseDetectionMethod: Generated<string>;
  updatedAt: string;
}

export interface PullRequests {
  author: string;
  codingTime: number | null;
  deployTime: number | null;
  firstCommittedAt: string | null;
  firstReviewedAt: string | null;
  mergedAt: string | null;
  number: number;
  pickupTime: number | null;
  pullRequestCreatedAt: string;
  releasedAt: string | null;
  repo: string;
  repositoryId: string;
  reviewTime: number | null;
  sourceBranch: string;
  state: string;
  targetBranch: string;
  title: string;
  totalTime: number | null;
  updatedAt: string | null;
  url: string;
}

export interface Repositories {
  createdAt: Generated<string>;
  id: string;
  integrationId: string;
  organizationId: string;
  owner: string;
  provider: string;
  releaseDetectionKey: Generated<string>;
  releaseDetectionMethod: Generated<string>;
  repo: string;
  updatedAt: string;
}

export interface Sessions {
  activeOrganizationId: string | null;
  createdAt: string;
  expiresAt: string;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: string;
  userAgent: string | null;
  userId: string;
}

export interface Users {
  banExpires: string | null;
  banned: number | null;
  banReason: string | null;
  createdAt: Generated<string>;
  email: string;
  emailVerified: number;
  id: string;
  image: string | null;
  name: string;
  role: string;
  updatedAt: string;
}

export interface Verifications {
  createdAt: string | null;
  expiresAt: string;
  id: string;
  identifier: string;
  updatedAt: string | null;
  value: string;
}

export interface DB {
  accounts: Accounts;
  companyGithubUsers: CompanyGithubUsers;
  exportSettings: ExportSettings;
  integrations: Integrations;
  invitations: Invitations;
  members: Members;
  organizations: Organizations;
  organizationSettings: OrganizationSettings;
  pullRequests: PullRequests;
  repositories: Repositories;
  sessions: Sessions;
  users: Users;
  verifications: Verifications;
}
