/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Accounts {
  accessToken: string | null;
  accessTokenExpiresAt: string | null;
  accountId: string;
  createdAt: string;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: string | null;
  scope: string | null;
  updatedAt: string;
  userId: string;
}

export interface AtlasSchemaRevisions {
  applied: Generated<number>;
  description: string;
  error: string | null;
  errorStmt: string | null;
  executedAt: string;
  executionTime: number;
  hash: string;
  operatorVersion: string;
  partialHashes: string | null;
  total: Generated<number>;
  type: Generated<number>;
  version: string;
}

export interface Invitations {
  createdAt: Generated<string>;
  email: string;
  expiresAt: string;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
  teamId: string | null;
}

export interface Jwks {
  createdAt: Generated<string>;
  expiresAt: string | null;
  id: string;
  privateKey: string;
  publicKey: string;
}

export interface Members {
  createdAt: string;
  id: string;
  organizationId: string;
  role: "owner" | "admin" | "member";
  userId: string;
}

export interface OauthAccessToken {
  clientId: string;
  createdAt: Generated<string>;
  expiresAt: string;
  id: string;
  referenceId: string | null;
  refreshId: string | null;
  scopes: string;
  sessionId: string | null;
  token: string;
  userId: string | null;
}

export interface OauthClient {
  clientId: string;
  clientSecret: string | null;
  contacts: string | null;
  createdAt: Generated<string | null>;
  disabled: Generated<number | null>;
  enableEndSession: number | null;
  grantTypes: string | null;
  icon: string | null;
  id: string;
  metadata: string | null;
  name: string | null;
  policy: string | null;
  postLogoutRedirectUris: string | null;
  public: number | null;
  redirectUris: string;
  referenceId: string | null;
  requirePkce: number | null;
  responseTypes: string | null;
  scopes: string | null;
  skipConsent: number | null;
  softwareId: string | null;
  softwareStatement: string | null;
  softwareVersion: string | null;
  subjectType: string | null;
  tokenEndpointAuthMethod: string | null;
  tos: string | null;
  type: string | null;
  updatedAt: string | null;
  uri: string | null;
  userId: string | null;
}

export interface OauthConsent {
  clientId: string;
  createdAt: Generated<string>;
  id: string;
  referenceId: string | null;
  scopes: string;
  updatedAt: string | null;
  userId: string | null;
}

export interface OauthRefreshToken {
  authTime: string | null;
  clientId: string;
  createdAt: Generated<string>;
  expiresAt: string;
  id: string;
  referenceId: string | null;
  revoked: string | null;
  scopes: string;
  sessionId: string | null;
  token: string;
  userId: string;
}

export interface Organizations {
  createdAt: Generated<string>;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface Sessions {
  activeOrganizationId: string | null;
  activeTeamId: string | null;
  createdAt: string;
  expiresAt: string;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: string;
  userAgent: string | null;
  userId: string;
}

export interface TeamMembers {
  createdAt: string | null;
  id: string;
  teamId: string;
  userId: string;
}

export interface Teams {
  createdAt: string;
  id: string;
  name: string;
  organizationId: string;
  updatedAt: string | null;
}

export interface Users {
  banExpires: string | null;
  banned: number | null;
  banReason: string | null;
  createdAt: Generated<string>;
  email: string;
  emailVerified: number;
  id: string;
  image: string | null;
  name: string;
  role: "admin" | "user";
  updatedAt: string;
}

export interface Verifications {
  createdAt: string | null;
  expiresAt: string;
  id: string;
  identifier: string;
  updatedAt: string | null;
  value: string;
}

export interface DB {
  accounts: Accounts;
  atlasSchemaRevisions: AtlasSchemaRevisions;
  invitations: Invitations;
  jwks: Jwks;
  members: Members;
  oauthAccessToken: OauthAccessToken;
  oauthClient: OauthClient;
  oauthConsent: OauthConsent;
  oauthRefreshToken: OauthRefreshToken;
  organizations: Organizations;
  sessions: Sessions;
  teamMembers: TeamMembers;
  teams: Teams;
  users: Users;
  verifications: Verifications;
}
