version: '3.9'
services:
  server:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:/upflow/data/data.db?connection_limit=1
    ports:
      - '8080:8080'
    volumes:
      - ./data:/upflow/data
    tty: true
